# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='entry',
        ),
    ]
